### ISSUE TITLE
Starting location based out of Maryland

### ISSUE THREAD

**Issue by chrismaltais** [ACalverley/wherecouldihavegone#1]
Although I'm based out of Kingston, the site consistently thinks I'm in Maryland due to Heroku's servers being based out of this location

**Example:**
<img width="1103" alt="screen shot 2018-03-12 at 9 11 53 pm" src="https://user-images.githubusercontent.com/17098959/37317258-38035bf6-263a-11e8-8c3a-d2492bcc4d70.png">

Possible Fix: Location can be grabbed from the browser using [HTML 5 geolocation](https://www.w3schools.com/html/html5_geolocation.asp)

**Comment by ACalverley** [comment]
User location is now collected through a browser prompt (inside 'initMaps') instead of a call to Google Maps Geolocation API which was faulty as it routed through the Heroku server location
